Feature/choose button
nightlaro/ColorTaste pull request #1
Opened 2021-07-29 02:25 UTC by nightlaro

https://user-images.githubusercontent.com/53090061/127421732-73eb0f5c-9cdf-412b-b629-7986e6354928.mov

For some reason my buttons background/background tint colors arent applying.
On the IDE the buttons sometimes shows up with the correct background color but then when I launch and build, every button is back to purple

2021-07-29 02:26 UTC, nightlaro commented
![Screen Shot 2021-07-28 at 7 26 25 PM](https://user-images.githubusercontent.com/53090061/127421918-368f7e76-7b86-4959-8421-197634cc8fc7.png)

2021-07-29 18:55 UTC, asarazan commented on app/src/main/java/com/example/colortaste/DefaultColorsActivity.kt
> +        val redButton = findViewById<Button>(R.id.red_button)
I miss synthetics so much 😭

2021-07-29 19:00 UTC, asarazan commented on app/src/main/java/com/example/colortaste/DefaultColorsActivity.kt
> +        val redButton = findViewById<Button>(R.id.red_button)
Btw if you wanted to get crazy with it, you could do something like this:
```kt
val buttons = listOf(
  R.id.red_button,
  R.id.orange_button,
  ...etc).map { findViewById<Button>(it) } 

buttons.forEach { it.setOnClickListener(::onClick) }
```

2021-07-29 22:18 UTC, vaudevillen commented on app/src/main/java/com/example/colortaste/DefaultColorsActivity.kt
> +    private lateinit var buttons_container : View
should be camel-case not snake-case

2021-07-29 22:22 UTC, vaudevillen commented on app/src/main/java/com/example/colortaste/MainActivity.kt
> +    }
nice! but does this set the color when you close and reopen the app? Like if you quit the app/force close it and restart it?

2021-07-29 22:25 UTC, vaudevillen commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.ColorTaste" parent="Theme.MaterialComponents.DayNight.DarkActionBar.Bridge">
what is "bridge"?

2021-07-29 22:27 UTC, vaudevillen commented on app/src/main/res/layout/activity_default_colors.xml
> +            android:textColor="#CFD8DC" />
use color resources and not hex codes. elsewhere you're using resources, like `@color/violet`

2021-07-29 22:36 UTC, nightlaro commented on app/src/main/java/com/example/colortaste/MainActivity.kt
> +    }
Unfortunately does not - yet, also rotating screen will reset background color, but we can totally accommodate that

2021-07-29 22:39 UTC, nightlaro commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.ColorTaste" parent="Theme.MaterialComponents.DayNight.DarkActionBar.Bridge">
That big red thing in San Fran that everyone takes a pic with... lol jk

tbh I am not entirely sure, got this solution through Matthew from [this](https://github.com/material-components/material-components-android/issues/889)

It fixed my buttons background color to be the correct one (the one that I set it to) and not the theme's primary color

2021-07-30 21:53 UTC, vaudevillen commented on app/src/main/java/com/example/colortaste/MainActivity.kt
> +    }
Here's a question for you: can you think of any other lifecycle callbacks you can use? Why did you choose `onRestart`?

2021-07-30 21:54 UTC, vaudevillen commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.ColorTaste" parent="Theme.MaterialComponents.DayNight.DarkActionBar.Bridge">
okay, this `bridge` thing seems to be legit

2021-07-30 21:54 UTC, vaudevillen commented on app/src/main/res/layout/activity_default_colors.xml
> +            android:backgroundTint="@color/red"
do you need to set both ` background` and `backgroundTint`?

2021-07-30 21:55 UTC, vaudevillen requested changes
Pretty good, dude!! Just a couple of minor things to change (fixing snake-case naming, fix background color not surviving app rotations/app restarts)

2021-08-02 17:26 UTC, asarazan commented
What happened that necessitated a force push?

2021-08-02 17:42 UTC, nightlaro commented
> What happened that necessitated a force push?

Here's the story...
I made a commit with a full on message and somehow it ended up with only "k" and I thought it was a little rude, so I kind of panicked and Matthew Ha happened to be sitting next to me. He is a GIT expert, but not really -- He told me to do this and that, and at the end told me to do `git push -f` 

TL:DR - It wasn't on purpose and it was unnecessary

MATTHEW HA: "FULL DISCLSURE: You should not use -f if you're working on a shared branch"
- Timestamp: Just now

2021-08-02 17:43 UTC, matthewnha commented
No comment

2021-08-02 17:45 UTC, asarazan commented
TBH I would avoid using `push -f` no matter what the branch. Generally the only valid reason to do it is if you accidentally check in a secret token or something.

2021-08-02 17:49 UTC, nightlaro commented on app/src/main/res/layout/activity_default_colors.xml
> +            android:backgroundTint="@color/red"
Can now use just `background` when using `bridge` in theme (which I still am not sure what `bridge` really does)

2021-08-02 18:03 UTC, nightlaro commented on app/src/main/java/com/example/colortaste/MainActivity.kt
> +    }
`onResume` would be a better choice, because ON_RESUME always gets invoked right after `onStart` so basically this would run everything the app gets restarted caused by screen rotation, new activity, phone calls etc

2021-08-02 18:49 UTC, vaudevillen commented on app/src/main/java/com/example/colortaste/MainActivity.kt
> +        const val COLOR_KEY = "lolhahahahalolkeklolencrypted"
you don't need to go to such lengths to secure the data for this

2021-08-02 18:52 UTC, vaudevillen commented on app/src/main/java/com/example/colortaste/MainActivity.kt
> +    override fun onResume() {
Nicely done changing this from `onRestart`. Even better than `onResume` would be `onStart`. It's called before `onResume`. Generally, `onStart` is a great place to check for data changes to update ui. We'll talk more about the differences between this stuff when we go more indepth into lifecycles

2021-08-02 18:54 UTC, vaudevillen commented on app/src/main/res/layout/activity_default_colors.xml
> +            android:layout_marginBottom="25dp"
since you're reusing this dimen everywhere, it'd be best to extract it into its own dimen resource

2021-08-02 18:55 UTC, vaudevillen commented on app/src/main/res/layout/activity_default_colors.xml
> +    <LinearLayout
Nesting this layout inside of the constraint layout is unnecessary. If you're only using the `LinearLayout`, that should be the parent layout and you should get rid of the `ConstraintLayout`

2021-08-02 19:00 UTC, vaudevillen requested changes
Looking really good! Just a couple minor changes:
- call `setBackgroundColor()` in `onStart` instead of `onResume`. That way it gets called earlier and the system will hopefully have more time to update the ui before the user sees it (even updating ui in `onStart` can lead to the user seeing the ui flickering/updating)
- get rid of the unnecessary nested layouts

2021-08-03 20:13 UTC, vaudevillen commented on app/src/main/res/layout/activity_default_colors.xml
> +    android:gravity="center|center_vertical"
don't need this... but not blocking merge

2021-08-03 20:13 UTC, vaudevillen commented on app/src/main/res/layout/activity_default_colors.xml
> +    android:baselineAligned="false"
don't need this... but not blocking merge

2021-08-03 20:13 UTC, vaudevillen approved these changes
LGTM!!!!

2021-08-03 20:55 UTC, merged